### ISSUE TITLE
Calling library from an external language

### ISSUE THREAD

**Issue by domluna** [dalek-cryptography/bulletproofs#95] opened 2018-06-02 17:26 UTC
More of a query than an issue. I'm looking into using this to compute proofs for ML applications. The ML will be done in an external language so I was wondering if there's a C/Rust API I could use to call this library.

**Comment by oleganza** [comment] 2018-06-03 06:34
That's a very good feature to have. Unfortunately, that's a little bit more complicated than simply providing a couple of `extern "C"` functions (lets say, `rbp_create_proof` and `rbp_verify_proof`) as our API consists of several high-level pieces. E.g. you pass a `ProofTranscript` object into the proving/verifying API, and supposed to commit the context of your protocol using this object. Exposing all these things via C-compatible interface is not going to be easy or pretty.

Meanwhile, if I were integrating this with a non-Rust codebase, I would probably define a project-specific adapter in Rust and expose it with a specific `extern "C"` function(s), hiding all the wiring between proofs, transcripts, error messages etc within that function, and exposing through C ABI only what is necessary for that project.

**Comment by domluna** [comment] 2018-06-03 15:18
Thanks, Oleg that make sense. Would something akin to `rbp_create_proof` and `rbp_verify_proof`would be somewhere on the roadmap is it that too general?

**Comment by oleganza** [comment] 2018-06-04 22:30
Upon thinking more about the problem you raised, I dumped some thoughts here: https://github.com/chain/ristretto-bulletproofs/issues/96 
What do you think?

**Comment by hdevalence** [comment] 2018-12-03 20:10
Closing this as a duplicate of #96

**Closed by hdevalence** 2018-12-03 20:10 UTC
