### ISSUE TITLE
Clarify rangeproof buildup

### ISSUE THREAD

**Issue by oleganza** [dalek-cryptography/bulletproofs#54] opened 2018-04-16 22:27 UTC
**Problem**

People have tried to dig into the algebra behind the RP and were confused at the very beginning.

Cf. https://twitter.com/NicolasDorier/status/984985725341806592

Also @bobg once mentioned that a prior, more elaborate, version of the notes was more educating.

**Suggestions**

1. Clarify transition from `v` to its bits, and the semantics of each equation.
2. Clarify the inner product notation at first use. E.g. `<a,b> = a_0*b_0 + ... a_{n-1}*b_{n-1}`.
3. Clarify the cryptographic trick of combining `n` statements with an `n-1`-degree polynomial. 
4. Would be good to conclude the IPP section with the rewrite of the final equation in the original RP notation which is replaced in the beginning of the section. This way it will be easy to tie this to actual RP protocol description and all the preceding notes.

**Comment by cathieyun** [comment] 2018-08-14 21:31
Closing, because the issue is addressed in https://github.com/dalek-cryptography/bulletproofs/pull/56

**Closed by cathieyun** 2018-08-14 21:31 UTC
Labels: docs
